server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    # 配置服务网关路由有两种：一种是yml配置，一种通过代码配置  使用gateway后端口号将变成gateway的
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务注册中心动态创建路由的功能，利用微服务名进行路由
      # 还可以在路由中配置过滤器 filters 见官网
      routes:
        - id: payment_routh          #payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # uri的协议为lb,表示启动gateway的负载均衡功能，后面为服务名称
          predicates:
            - Path=/payment/getById/**     # 断言，路径相匹配的进行路由

        - id: payment_routh2        #payment_route  路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          # predicates是断言，有After,Before,Between,Cookie,Header，Method,Host等属性 看官网
          # Cookie需要两个参数，一个是Cookie name，一个是正则表达式，路由规则会通过获取对应的Cookie name值和正则表达式去匹配，如果匹配上才会执行路由
          # 打开cmd使用curl（postment的命令行）访问： curl http://localhost:9527/payment/LB --cookie "username=zzyy"
          predicates:
            - Path=/payment/LB/**     #断言，路径相匹配的进行路由
#            - After=2021-07-17T17:21:37.820+08:00[Asia/Shanghai] # 表示要在这个时间之后访问才能生效（使用ZonedDateTime zdj = ZonedDateTime.now()获取格式）
#            - Cookie=username, zzyy
#            - Header=X-Request-Id, \d+   # 请求头要有X-Request-Id属性并且值为整数的正则表达式，\d+表示正整数的表达式,curl http://localhost:9527/payment/LB -H "X-Request-Id:45"
#          filters:
#            - AddRequestParameter=X-Request-Id, 1024 # 过滤器工厂会在匹配的请求头加上一对请求头，名为X-Request-Id，值为1024
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka